# fly.toml app configuration file generated for solidqueue-goodjob-benchmark on 2026-01-14T12:55:35-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'solidqueue-goodjob-benchmark'
primary_region = 'iad'
console_command = '/rails/bin/rails console'

[build]

[env]
  HTTP_PORT = "8080"
  PORT = "8080"
  RAILS_ENV = "production"

[processes]
  web = "./bin/thrust ./bin/rails server"
  solidqueue = "./bin/jobs start"
  goodjob = "bundle exec good_job start --max-threads=20"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['web']

  [[http_service.checks]]
    interval = '10s'
    timeout = '2s'
    grace_period = '5s'
    method = 'GET'
    path = '/up'
    protocol = 'http'
    tls_skip_verify = false
    restart_limit = 3

    [http_service.checks.headers]
      X-Forwarded-Proto = 'https'

[[vm]]
  memory = '2gb'
  cpus = 2
  memory_mb = 2048

[deploy]
  release_command = "bin/rails db:prepare"
